### ISSUE TITLE
Tag a new release with 0.4 deprecations fixed

### ISSUE THREAD

**Issue by maximsch2** [dirkschumacher/PValueAdjust.jl#7]
The current version that one gets from `Pkg.add("PValueAdjust")` throws deprecation warnings and doesn't behave like the documentation on the GitHub page suggests. `Pkg.checkout("PValueAdjust")` fixes this issue, so it's just a matter of tagging a new version.

**Comment by dirkschumacher** [comment]
Hi Maxim,

thanks. Will tag a new version in the coming days.

Best
Dirk

**Comment by maximsch2** [comment]
Hi Dirk,
Can you please tag a new version again? Current master version works fine in 0.5.0, but currently tagged one (2.0.0) doesn't.

**Comment by dirkschumacher** [comment]
Oh man, sorry. I totally forgot that.

Looking around there seems to be another package: https://github.com/juliangehring/MultipleTesting.jl

It has everything this package has and it is actively maintained. Maybe I should just deprecate this package in favor of the other. I am currently not using Julia regularly and therefor I don't notice if something in julia changes. What do you think?

**Comment by maximsch2** [comment]
Thanks for the pointer, I wasn't aware of that other package. I guess the best thing would be to de-register this package from METADATA and put a pointer to that other one in the README on github to point people there?

**Comment by juliangehring** [comment]
@maximsch2 Dirk's excellent package was a strong motivation to start with MultipleTesting.jl. The two packages evolved out of different purposes, but with respect to pvalue adjustment both have equivalent functionality, and incidentally, similar interfaces by now.

**Comment by juliangehring** [comment]
@dirkschumacher Irrespectively of whether you want to continue maintaining your package, please feel very welcome to also be part of the MultipleTesting development! Especially if you find yourself short of time, but would like to continue working on the subject, we can simply join forces. :)

**Comment by dirkschumacher** [comment]
I added a note to the Readme.md and will ask in the METADATA repository how to deprecate packages.

**Comment by dirkschumacher** [comment]
Opened a pull request: https://github.com/JuliaLang/METADATA.jl/issues/7140
